baseURL = "https://leechristopher722.github.io/"
defaultContentLanguage = "en"

title = 'Christopher Dev Blog'
enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
